### ISSUE TITLE
bro, when publish new version?

### ISSUE THREAD

**Issue by hzc54188** [Joegenco/PixelManager#1]
![image](https://user-images.githubusercontent.com/24639554/232738140-2194b885-7a2a-49f1-9fd4-472501306ccb.png)
effect very nice,thank you very muck.

**Comment by Joegenco** [comment]
I'm beta testing at the moment to iron out issues that I could not spot on my own.

No specific release date atm, its ready when its ready. Expect bi-dialy updates to the main branch.
