### ISSUE TITLE
Blender 3.6 not reading.

### ISSUE THREAD

**Issue by TheRealOscarMike** [Joegenco/PixelManager#10]
Not sure what had happened. But I updated Blender to 4.0 and once I saw some of my plugins and such like Pixel Manager not there. I reverted. But then my version of Pixel Manager (From August) wasn't listed anymore. I downloaded the newest one and realized alot of the options from the version I had were gone/missing and I was left with a really poor selection, from what I had before. So I tried readding the files and Blender just doesn't recognize it and I'm stuck with the newest poor option version...

Not sure if this is the place to put this. but I couldn't find anywhere else to contact about this issue to get some help.

*I'm backon 3.6 (until other plugins get updated.)

**Comment by Joegenco** [comment]
Blender versions have different installations, Blender will install each version to a seperate folder and keeps their settings/plugins in seperate folders too.

%90 of the plugins that work with 3.6.6 will work with 4.0.
%90 of settings on 3.6.6 can be carried over to 4.0 in first open up.

Go to `C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender` to see your plugins and settings.

You will need to re-install PixelManager to Blender 4.0 or 3.6 each time you update it using a .msi or .exe file.

Please download the latest from the github repo and not the tags, tags are not updated to latest atm.

**Comment by TheRealOscarMike** [comment]
I tried the tags to see if I was messing something up. But I'm pulling from the masters. And lime I said half of my things that were from my initial download aren't there. And I reinstalled them to the same place, they show up in blender. I just want all my older files back, seems like there were alot more options.

If there is other d0wnloads besides masters. I ain't seeing them

**Comment by Joegenco** [comment]
If youre talking about the inactive colorspaces you may go into the ocio config file and pick an inactive colorspace section. Add a # before the inactive colorspace which defines the "minimal" to reveal all the colorspaces.

![image](https://github.com/Joegenco/PixelManager/assets/33637910/00b7c55b-5a3d-489a-81ab-49fa48eb4084)
![image](https://github.com/Joegenco/PixelManager/assets/33637910/8cf185e0-5e64-439a-9edd-024f33b7a3c9)

If this is regarding your other blender issues regarding plugins, this is not the place the troubleshoot the problem youre having. I tried helping with my first post but I cannot help further than that.

**Comment by TheRealOscarMike** [comment]
I think this will fix my issue. Cause I do remember seeing like 100 options under ACES like 20,30,40,50 Black and White options. Commerical 2111/commercial 2011 and such. A lot of what I see now it just grey scale/ punch/none. I will get back to you. Thanks for taking the time to get back to me.

And I know this might not be the place to trouble shoot. But I wasn't sure where else to start.

**Comment by TheRealOscarMike** [comment]
![6464565](https://github.com/Joegenco/PixelManager/assets/40978998/de13882b-2858-436a-9350-a49e30e7a162)
Sorry for the wall of text. For some reason my text editor would display that part of the file. I messed around with the # thing, and it didn't seem to fix anything. I'm still missing the shit I had before. When all I did was update to 4.0 and then switch back. 
![20231118_080934](https://github.com/Joegenco/PixelManager/assets/40978998/d1749792-751b-48ba-97b8-e31c40adc5af)
![20231118_080941](https://github.com/Joegenco/PixelManager/assets/40978998/24588ad0-3e50-43e5-88cf-8efa91a58e65)
![20231118_080927](https://github.com/Joegenco/PixelManager/assets/40978998/abc7b14d-51ce-48f5-a1cb-f62b948dd7b9)

If this don't fix it. I guess i'll be off to find another color management type addon. Cause what I'm getting from it now is jack compared to what I had before.

**Comment by Joegenco** [comment]
"Look" creative luts of RED IPP2 and ARRI has been removed after the overhaul. I leads into a large file size for pixelmanager and does not contribute much to the idea of it.

Current looks are only available for the image formations that makes sense with them.

Feel free to revert back to the old one if you absolutely need the creative looks.

**Comment by TheRealOscarMike** [comment]
I would like to revert. But I can't find it on my computer, and I was looking on here.

**Comment by Joegenco** [comment]
https://github.com/Joegenco/PixelManager/tree/867f1616997c32d0dac761485b4cfde7f7ee11fd

You may combine the looks from here to the latest from master if you wish.

**Comment by TheRealOscarMike** [comment]
Thanks my dude. This is what I was looking for. Much appreciated!
Cheers.
