### ISSUE TITLE
Unreal Viewport cause blown out images when pixel values are negetive

### ISSUE THREAD

**Issue by NodeDadu** [Joegenco/PixelManager#11]
Example ( Blue bar from testing imagery repo )

![Screenshot 2023-11-19 212800](https://github.com/Joegenco/PixelManager/assets/48753341/b5936d0b-1511-4229-9649-4dd3a6c38981)

**Comment by Joegenco** [comment]
Are you spesifically talking about the "Unreal Engine" View?

Or unreal viewport displaying things incorrenctly in UE, if so whats the UE version? for me to reproduce.

UE, look is not perfect its "reverse engineered" by comparing a natrual 33*33*33 16bit cube with the same cube exported using the tone mapper of UE. 

I might need to re-adjust the lut so it clips out out of gamut values.

Ill look into it further.

**Comment by NodeDadu** [comment]
Talking about the Unreal Engine Viewport "View" from the config, not unreal engine itself.

While unsure about the accuracy, does need to clip out of gamut values or this happens

**Comment by Joegenco** [comment]
Adressed in 8c11a07 please confirm and I will create another release candidate.

**Comment by Joegenco** [comment]
No response for 1 week. Resolving it as my testing shows that this is now fixed.
![BlueFlipTest](https://github.com/Joegenco/PixelManager/assets/33637910/5bbbf15e-34ad-4caf-a126-f1843e24d0ba)
