### ISSUE TITLE
aces 1.3 rgc in ocio v2.0

### ISSUE THREAD

**Issue by piotrus3333** [Joegenco/PixelManager#12]
aces 1.3 reference gamut compression should not be performed in acescc/acescct. and with larger cube. I suggest logC4:
[mP_LogC4_acesRGC.zip](https://github.com/Joegenco/PixelManager/files/13463931/mP_LogC4_acesRGC.zip)

**Comment by Joegenco** [comment]
Adressed in 8c11a07 please confirm and I will create another release candidate.

**Comment by piotrus3333** [comment]
all good. thank you.
