### ISSUE TITLE
Suggestion - Add Linear spaces in views

### ISSUE THREAD

**Issue by NodeDadu** [Joegenco/PixelManager#15]
Add all the different linear spaces as views in the view section. This is a very useful utility for a variety of purposes.

**Comment by Joegenco** [comment]
Some software will clip float values to the rendering space, like blender. And even if its not clipped, linear should be exported as floatin poing point (like exr) (if its an actual colorspace and not "data") and it could be transformed in the destination.

I dont see the use for it. Could you give an example?

**Comment by NodeDadu** [comment]
Personally it is very useful when you are doing image formation in the compositor (and doing post formation adjustments), helps with previewing. It is also useful for viewing data when working with shaders. 2 things from the top of my mind.

it is more useful for viewing/debug than it is for any exporting

**Comment by Joegenco** [comment]
"None" in alll "views" exists so that will disable any management essentially.

Otherwise, commenting out all "inactive_colorspaces" is an option.

Perhaps I can add another "inactive_colorspaces" preset which has all linear spaces visible.

**Comment by NodeDadu** [comment]
There is a reason to have linear spaces as opposed to just none when you are comp image forming for a display that has a different gamut than your own display. Very niche but can be needed.

**Comment by Joegenco** [comment]
Again, why would you want to look at a "Linear" image without gamma. Keep in mind, your monitor is applying inverse gamma to your image and what the monitor shoots out (in a perfect scenerio) is linear image.

Lets think about a scenerio:

sRGB Display:
Input 2,2 gamma sRGB Texture -> Working space Linear -> Display gamma/colorspace -> Displays inverse gamma -> Your eyes
If your workspace was sRGB/Rec709 the colorspace isnt touched with a 3x3 matrix at all in this proccess.

Input Linear sRGB Texture -> Working space linear -> Display gamma/colorspace -> Displays inverse gamma -> Your eyes.
In this one if your working space is same as the input texture space, it wasnt touched in first step.
If your workspace was sRGB/Rec709 the colorspace isnt touched with a 3x3 matrix at all in this proccess.


If you want to see the input texture as is without massaging then "Standard" view will give you that.
This applies for all other "Standard" views across other display options.

No matter what it is, if you define the input space if the texture, light output from your monitor (in a perfect world) will be linear.

I am not sure if I follow your needs right, or if i was able the describe what I mean well.

**Comment by Joegenco** [comment]
Closing for now until 1.1.0
