### ISSUE TITLE
Installation on Blender 4.0

### ISSUE THREAD

**Issue by TheRealOscarMike** [Joegenco/PixelManager#16]
I've spoke to you before about an installation issue on that one color management pack you've had before. With all the different CUBE files. like fashion, Film A, Film B, Film C, and many more like that, I believe those choices were under ARRI_Reveal_LookLib. I got it working after we last spoke. But I've since upgraded my system/version, and I've followed the same installation path as before, and they do not sure up what so ever. Does something in Blender v4 change how color management works?

**Comment by Joegenco** [comment]
I dont intend to add back the "looks" for the time being. Vendor looks are removed with the overhaul.
