### ISSUE TITLE
Can't use in Blender/Octane any more

### ISSUE THREAD

**Issue by AndreasReschGFX** [Joegenco/PixelManager#18]
Unfortunately I can't use the PM in Blender/Octane any more it won't let me select the ACES2065-1/Colorspace settings any more. It always goes to Linear sRGB. Any ideas how to fix this?
![PM_Settings_01](https://github.com/Joegenco/PixelManager/assets/23632045/3ebecab4-4c8c-4773-961c-b3363e1a7cba)

**Comment by AndreasReschGFX** [comment]
After deactivating line 201 it works. Not sure why it's deactivated from the get-go. Any reasons for that?

**Comment by Joegenco** [comment]
I will have a look. Busy until the end of the week.

Thank you for the report!!

**Comment by Joegenco** [comment]
Line 201 which is
`    - !<View> {name: S-Log2 ITU-709, colorspace: S-Log2 ITU 709 Matrix}`

Is that right?

**Comment by Joegenco** [comment]
Closing as the conversation went stale
