### ISSUE TITLE
What's the reason of using AgX-SB2383 Base for color_timing and compositing_log?

### ISSUE THREAD

**Issue by Baalvon** [Joegenco/PixelManager#2]
By default, the config uses AgX-SB2383 Base instead of sRGB or ACES for color_timing and compositing_log. Does it produce better result?

**Comment by Joegenco** [comment]
AgX-SB2383 uses Rec709/sRGB as the colorspace. The gamma is its own log curve. So between sRGB and AgX-SB2383 as color_timing theres no difference. 

By ACES you mean, ACEScc or ACEScct which uses ACES-AP1 colorspace which has a wider gamut and leads into quite a lot of problems for renders.

When it comes to compositing_log. I find AgX-SB2383 much more robust and "less breaking" than any ACES-Log space.

You may try Filmights Log or even something like LogC from Arri or sLog from Sony. See what works best for your needs.
