### ISSUE TITLE
Missing Display devices and Vew Transforms

### ISSUE THREAD

**Issue by panbeep** [Joegenco/PixelManager#21]
Hi,
I was using older version which is not available anymore that had 2.2 Rec709 Display device and Sony, RED and BMD View Transforms.
How can I get it back in new version?

**Comment by Joegenco** [comment]
"Standard" in all displays is the native power funtion for the display now. Its just a simple power function with all values above 1.0 clipped. "sRGB" Display and "Standard" View is "2.2 Rec709" essentially.
Pick what your display device is and pick a view for the type of image formation you want.
IE: if youre on MAC you most likely want Display P3, if youre on windows and your monitor is wide gamut check what it actualy displays as blender (or most other DCC's) bypass windowses color management.

Red is still there, IPP2 is essentially RED but its only the "Medium contrast - Medium sharpness" supplied by RED. Adding all 8 variations Red supplies crowds things too much.

Sony and BMD image formations are gone indeed, I will add them for the next minor version for you.

**Comment by Joegenco** [comment]
"Looks" most likely are not coming back as most software doesnt support the "looks" section.

Perhaps I will include a route to easier creation of LUTs in the readme

**Comment by panbeep** [comment]
I use Blender and Octane Render and they both support looks.
