### ISSUE TITLE
Crash when opening file that uses "Conver Colorspace" Node in compositor

### ISSUE THREAD

**Issue by Thane5** [Joegenco/PixelManager#22]
I have a coupld of files where i manually convert the image from raw to the compositor. These files crash almost instantly after switching to this OCIO config. 
![image](https://github.com/Joegenco/PixelManager/assets/13683581/b080b57f-6a36-4d09-b154-c6b8ce09293b)

**Comment by Joegenco** [comment]
Could you provide the a log for the crash, your blender version and which
version of pixel manager you're using. I'll try to replicate it and figure
out what's wrong.

**Comment by Thane5** [comment]
[scene_chapter04_oldgrass.crash.txt](https://github.com/Joegenco/PixelManager/files/14929434/scene_chapter04_oldgrass.crash.txt)
 here's a log. Blender 4.0.2. Latest release of your config.

**Comment by Thane5** [comment]
Here is the simplest way to replicate it: 

- Load the default OCIO config
- open blender
- in compositor, check "use nodes"
- add a "convert colorspace" node in between the two default nodes
- In the node, set the target colorspace to "AGX Base sRGB"
- Save file, restart with Pixel managers OCIO config
- Render the same file. Blender will now crash.

**Comment by Joegenco** [comment]
I think I know what might be the issue.

I hid some spaces in the default PixelManager config which may be available in default Blender.

Please try [v.1.1-RC.2 ](https://github.com/Joegenco/PixelManager/releases/tag/v.1.1-RC.2) and tell me if that fixes your issue.

**Comment by Thane5** [comment]
The crash is fixed. But i noticed that files with this node setup suddenly appear brighter when rendered with the new OCIO config.

This is likely because my scenes that use the "Raw" view transform get converted to "standard" when i switch to your config. I guess this is simply sRGB?

**Comment by Joegenco** [comment]
If youre applying image formation in the compositor, its best to use "none" for the view transform. (Which is the old "raw")
Otherwise there will be formation applied twice.

There is a change to what "sRGB" is tho. It was originally a piecewise function in Blender, I made it pure power like most monitors inverse curves are. more info at #17 

you can close the issue if you see it resolved. But do let me know if you have another request
