### ISSUE TITLE
Not all color profiles available in Blender Compositor or VSE

### ISSUE THREAD

**Issue by ichlubna** [Joegenco/PixelManager#24]
Hello,
firs of all, thanks for this amazing pack. I would like to ask how to enable all profiles to be used in Compositor and VSE. For example, the camera log profiles are available here:
![image](https://github.com/user-attachments/assets/c79a383a-a214-430b-b4b2-9b8bc03f62fd)
But I cannot access them in the Compositor:
![image](https://github.com/user-attachments/assets/3c091f87-8b7b-4580-96f1-91dfa94421d9)
Nor in the VSE:
![image](https://github.com/user-attachments/assets/fd4c4d16-1a6c-4be3-a72d-50b7a6491fbd)
I would like to render a sequence in a specific space and be able to import it and convert to a different one. What I mean is to be able to do something like this:
![image](https://github.com/user-attachments/assets/ea6cc0fb-15a5-401e-bb01-47c101fb8251)

Is this even possible? 
Thanks!

**Comment by Joegenco** [comment]
Please read the readme in the main GitHub page

**Comment by ichlubna** [comment]
> Please read the readme in the main GitHub page

Thanks and sorry. I missed that.
