### ISSUE TITLE
Proper DCI-P3 should use DCI whitepoint

### ISSUE THREAD

**Issue by EaryChow** [Joegenco/PixelManager#5]
Just took a quick look, it seems the DCI-P3 is defined as D65 white point with power 2.6 TF. 

Proper DCI-P3 should have DCI white point, in my understanding, we should arrive at DCI illuminant adapted XYZ first.

First from CIE-XYZ E to CIE-XYZ DCI, method of this matrix is Bradford:
```
[[ 0.93137082 -0.04181835  0.00503453]
 [-0.0638608   1.0589086   0.00495221]
 [-0.00358392  0.00889451  0.94910541]]
```

Then from CIE-XYZ DCI to Linear DCI-P3 DCI
```
[[ 2.7253940304917332 −1.0180030062271852  −0.4401631951900365]
 [−0.7951680258087643   1.6897320548436243   0.0226471906084774]
 [0.0412418913957000  -0.0876390192158624  1.1009293786463223]]
```

**Comment by Joegenco** [comment]
Thank you very much!

I believe its fixed now. Please confirm and Ill create RC-2

**Comment by EaryChow** [comment]
I am not sure about whether those P3 D65 view transform LUTs should also go through the adaptation, if the LUT names specifically say D65, maybe just simply adjust the transfer function, since they are already D65.

**Comment by Joegenco** [comment]
Youre right, Although its not referenced anywhere else, it was not correct.

How about now. Added a seperate `DCI-P3 D65 2.6` in [bfc0c74](https://github.com/Joegenco/PixelManager/commit/bfc0c74a59992c7bc7e5fc8fcf6a958b5c4966b1)

**Comment by EaryChow** [comment]
I am seeing, Reveal for instance
```
        - !<FileTransform> {src: ARRI_LogC4-to-Gamma26_P3-D65_v1-33.cube, interpolation: tetrahedral}
        - !<ColorSpaceTransform> {src: DCI-P3 2.6, dst: Display P3}
```
It seems Reveal outputs P3 D65 Power 2.6, then we interpret it as DCI 2.6, go through DCI to D65 adaptation, and then encode sRGB transfer function. So this looks like it has an additional DCI to D65 applied.

**Comment by Joegenco** [comment]
Then we were correct in the first place, just the naming was confusing.

Ill go trough all the P3 views and see which one is actually spitting out DCI and which one is P3-D65. I got confused here.

**Comment by Joegenco** [comment]
Turns out only Canon was using the DCI whitepoint. Rest is corrected.

Wonder if we should add DCI as a view for the image formers. It would be very niche.

Closing it now.

Thank you very much!
