### ISSUE TITLE
error when opening in nuke

### ISSUE THREAD

**Issue by saldvd** [Joegenco/PixelManager#6]
sorry if this is the wrong place to put this but when I try opening the ocio file in nuke. theres an error saying it the wrong version. can I not use this setup in nuke or is this just for blender?

**Comment by Joegenco** [comment]
It's the ocio version 2.1 nuke has 2.0 (I think)

You can switch the version number on top of the .ocio file by opening it
with a notepad.

You will loose ACES gamut compression look only.

You will need to remove this look from all the way on the end of the .ocio
file in the "looks" section.

Tell me how it goes please. I didn't test with Nuke.

**Comment by saldvd** [comment]
thank I'll give it a try and let you know.

**Comment by saldvd** [comment]
Hey I just wanted to let you know that work for nuke. thanks for all your hard work.

**Comment by Joegenco** [comment]
Great! Hopefully Nuke will move onto OCIO 2.1+ soon.

I'll include this in the read-me for Nuke users.
