### ISSUE TITLE
ACES -- exposure & gamma adjustment not working.

### ISSUE THREAD

**Issue by nurb2kea** [Joegenco/PixelManager#8]
Hi,

just tested your setup. In ACES when using the sliders for exposure & Gamma, nothing happens.
In my setup it's working.
So I guess there is something missing.

Here is mine. It's a funny setup ... but maybe you can see what's missing.

[config.ocio.txt](https://github.com/Joegenco/PixelManager/files/13197102/config.ocio.txt)

![Screenshot 2023-10-29 at 4 04 57 am](https://github.com/Joegenco/PixelManager/assets/57676085/bcab6487-899f-4ff8-a798-d6b7167cf944)

**Comment by Joegenco** [comment]
I cannot replicate this, 
Which software are you using? Which version of software?
Which version of PixelManager?

**Comment by nurb2kea** [comment]
Hi,

yesterday I downloaded the master from here.
![Screenshot 2023-10-29 at 7 38 46 pm](https://github.com/Joegenco/PixelManager/assets/57676085/555a585e-d5f6-4684-b040-8ff0d92d2a03)
With Blender 3.6.5 silicon on MacOS 14.1 silicon M2

Here with your setup:
https://github.com/Joegenco/PixelManager/assets/57676085/a1182c2c-7be4-419f-94d0-2377bbcb5c2b

Here with my ocio setup:

https://github.com/Joegenco/PixelManager/assets/57676085/bf02e990-c1a7-42cd-8041-e6c89b73a253

**Comment by Joegenco** [comment]
Odd behaviour I cannot replicate on Windows atm.

Could you go to Window -> toggle system console and tell me if/what OCIO error youre seeing there when you switch to ACES?

**Comment by nurb2kea** [comment]
Only ACES & ACES GamutComp has errors. 
I tested the rest too. without an error, BUT when changing to every look for every profile, there are more errors !
There is no console on Mac, but the terminal.

here the error when switching from any profile to ACES:
ERROR (gpu.shader): OCIO_Display Fragment Shader: 
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_1(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_1(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_2(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_2(in int curveIdx, in float x)
      | ^

----------------------------------
----------------------------------
Switching between looks on other profiles gives more errors. I didn't test everything...

ERROR (gpu.shader): OCIO_Display Fragment Shader: 
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_2(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_2(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_3(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_3(in int curveIdx, in float x)
      | ^

ERROR (gpu.shader): OCIO_Display Fragment Shader: 
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_1(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_1(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_2(in int curveIdx, in float x)
      | ^
      | 
      | Error: unknown type name 'in'
      | 
      | float to_display_grading_rgbcurve_evalBSplineCurve_2(in int curveIdx, in float x)
      | ^

ERROR (gpu.shader): OCIO_Display Fragment Shader: 
      | 
      | Error: value of type 'bool __attribute__((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
      | 
      | if ( gamma != vec3(1., 1., 1.) )
      | ^~~~~~~~~~~~~~~~~~~~~~~~~

ERROR (gpu.shader): OCIO_Display Fragment Shader: 
      | 
      | Error: value of type 'bool __attribute__((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
      | 
      | if ( gamma != vec3(1., 1., 1.) )
      | ^~~~~~~~~~~~~~~~~~~~~~~~~

ERROR (gpu.shader): OCIO_Display Fragment Shader: 
      | 
      | Error: value of type 'bool __attribute__((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
      | 
      | if ( gamma != vec3(1., 1., 1.) )
      | ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Joegenco** [comment]
I think we have found a bug in the OCIO implementation of Blender 3.6.5's Mac version. Might be due to M2 aswell.

OCIO 2.0 has BuiltInTransform functions for ACES. And PixelManager direcly uses these, istead of including baked in luts. This improves accuracy and lowers the size of PixelManager.

We have two options here, we can either include the luts in PixelManager and dont use OCIO's already there functions. Or bug-report this to Blender to solve if its still an ongoing issue.

Since I dont have a mac I cannot test this.
Would you be able to check the 3.6.4 and 4.0 to see if the issue happens there too?

This is OCIO implementations fault.

**Comment by nurb2kea** [comment]
OK, 
but I'm away for an hour from now. Then I test it and come back to you in maybe 2 hours...

**Comment by nurb2kea** [comment]
I tested now silicon blender 3.6.3, 3.6.4, 3.6.5, 4.0b & 4.1a with the exact same issues. No difference in the errors !
![System 14 1](https://github.com/Joegenco/PixelManager/assets/57676085/7142c028-bd25-4aa0-9aae-711847f17b15)
![Screenshot 2023-10-29 at 10 10 59 pm](https://github.com/Joegenco/PixelManager/assets/57676085/0c4aed74-7dab-420f-8996-6805460103ee)
![Screenshot 2023-10-29 at 10 11 55 pm](https://github.com/Joegenco/PixelManager/assets/57676085/25875753-3137-4ace-ad74-b619e158e579)
![Screenshot 2023-10-29 at 10 11 41 pm](https://github.com/Joegenco/PixelManager/assets/57676085/36aaa5e5-21a1-4ec4-aacd-d2b972a72852)
![Screenshot 2023-10-29 at 10 11 29 pm](https://github.com/Joegenco/PixelManager/assets/57676085/965a62c3-883c-493f-904d-4ee5b6ef05cb)
![Screenshot 2023-10-29 at 10 11 12 pm](https://github.com/Joegenco/PixelManager/assets/57676085/33a838bc-021a-4d27-b35c-55bbd6fbfb2b)
![Screenshot 2023-10-29 at 10 07 52 pm](https://github.com/Joegenco/PixelManager/assets/57676085/cca94396-8705-41fa-938b-3041eaabf09a)

**Comment by EaryChow** [comment]
>  if ( gamma != vec3(1., 1., 1.) )
> I tested now silicon blender 3.6.3, 3.6.4, 3.6.5, 4.0b & 4.1a with the exact same issues. No difference in the errors !

Are you sure? 4.0 should work I believe, seems like an already fixed issue: 
https://github.com/EaryChow/AgX/issues/1#issuecomment-1496270384
https://projects.blender.org/blender/blender/commit/259bfc45534af90a4d2b0a3d92a763114bb0ff22

**Comment by nurb2kea** [comment]
What do you mean with are you sure!?
As you can see I opened every blender version listed above via Terminal to get to see the errors.
I made a screenshot from every blender version to show from what date and build...
Beforehand I switched every colormanagement folder item with your setup. (if I do a mistake there, blender won't start up)

Then I switched in each blender version the profiles the same way and get with each version the same errors you have seen above. I did not test all profiles with all their looks.
But when switching to ACES & ACESGamutComp I get the errors, also when switching their LOOKS.
With some other Profiles, the switch produces no error BUT when switching to some LOOKS.

Also it was Sergey Sharybin 2 months ago. Also I'm not sure if Sergey has access to MacOS on M2 silicon.
It's very common that they put up a fix, without testing. I had this many time with them and a lot of trouble. Because this  costs my time to remind them over and over to first test and then release. Even buildbot for Mac is bull....

Could easily be that they changed something or they reverted it.
Because the last weeks I have seen that brecht and others reverted some things for 4.0 to fix them in 4.1.

I don't know who [berenyiaustin](https://github.com/berenyiaustin) is, and how he tested it.

You can file a bugreport with all the data I gave you, and let THEM test it.

For the next 3-x days, I can't do that, because I get my 1600$ Monitor repaired, and have no access to another one.
But I will check back, when I can.

Hope that helps and clears up, how I tested and prepared each blender version from silicon blender 3.6.3, 3.6.4, 3.6.5, 4.0b & 4.1a with your setup.

read you later :-)

**Comment by Joegenco** [comment]
Thank you for the report @nurb2kea .

It seems this issue is on the radar of the blender devs and most likely will be merged to main very soon.

In the meantime, if you need to use ACES with Blender, please either edit the .ocio file to not use any BuiltInTransforms for ACES path, that is ACEScg, ACES2065, ACEScc, ACEScct, ACES sRGB, ACES Display P3, ACES Rec2020, ACES PQ. Any "BuiltInTransform" you see in the config will not be working with the current builds it seems.

I do value this report and thank you very much for writing. Please raise if you experience any other issues.

**Comment by nurb2kea** [comment]
Hi, 

just installed the latest Pixelmanager setup with new blender 3.6.6 and got some issues there as well.
see the settings in the images...
But this is an introduced blender issue, since yesterday !
Worst in 4.0b...

Blender 3.6.6 with latest and the version from above last week:
![Screenshot 2023-11-07 at 12 54 40 pm](https://github.com/Joegenco/PixelManager/assets/57676085/52fd0cca-9576-4970-b477-0ddbcb68b845)
![Screenshot 2023-11-07 at 12 54 54 pm](https://github.com/Joegenco/PixelManager/assets/57676085/14e2ea18-0ca7-412c-be72-2beb94aa38c2)
![Screenshot 2023-11-07 at 12 55 03 pm](https://github.com/Joegenco/PixelManager/assets/57676085/91536d23-4809-48d2-aeb7-db65959be362)
This is blender 4.0b
![blender 4 0b](https://github.com/Joegenco/PixelManager/assets/57676085/c4b52eb8-ce35-4699-bc24-aa69cb9101d3)

And this is ACES vs standard blender 3.6.6:
![Screenshot 2023-11-07 at 12 56 00 pm](https://github.com/Joegenco/PixelManager/assets/57676085/302949b3-03c5-4d77-9d8b-751f40436ac8)
![Screenshot 2023-11-07 at 12 56 15 pm](https://github.com/Joegenco/PixelManager/assets/57676085/a3581dc6-b4be-41d5-a1fc-8da81794cf5c)

This is blender 4.0b with it's onboard ocio and luts:
![Screenshot 2023-11-07 at 1 10 00 pm](https://github.com/Joegenco/PixelManager/assets/57676085/ac52a9be-ef69-4fb6-b445-672eefab7e02)
![Screenshot 2023-11-07 at 1 10 18 pm](https://github.com/Joegenco/PixelManager/assets/57676085/73f3fb9a-60ac-4c65-a122-2520d846031f)
![Screenshot 2023-11-07 at 1 10 31 pm](https://github.com/Joegenco/PixelManager/assets/57676085/bef77f13-6ca0-49ce-8cb3-427be0cbdeb4)
![Screenshot 2023-11-07 at 1 11 04 pm](https://github.com/Joegenco/PixelManager/assets/57676085/589325ee-8135-447d-8e05-12aa31f3b9d5)
![Screenshot 2023-11-07 at 1 11 13 pm](https://github.com/Joegenco/PixelManager/assets/57676085/06fa4dc1-0a12-42bc-b7a8-224f036373d5)
![Screenshot 2023-11-07 at 1 11 25 pm](https://github.com/Joegenco/PixelManager/assets/57676085/9ec5966a-b1be-4070-99a6-45e3f2e0ee88)
![Screenshot 2023-11-07 at 1 11 41 pm](https://github.com/Joegenco/PixelManager/assets/57676085/7712ab58-0703-43a9-90ec-4f3ca45a2476)
![Screenshot 2023-11-07 at 1 12 34 pm](https://github.com/Joegenco/PixelManager/assets/57676085/0e9e3154-741c-47cf-a73a-ea32111f161c)
![Screenshot 2023-11-07 at 1 13 52 pm](https://github.com/Joegenco/PixelManager/assets/57676085/1a15add1-5358-4dc8-b574-593e1a319592)
