### ISSUE TITLE
Did you see my update!?

### ISSUE THREAD

**Issue by nurb2kea** [Joegenco/PixelManager#9]
https://github.com/Joegenco/PixelManager/issues/8

**Comment by Joegenco** [comment]
This looks to be like a issue steming from the different hardware of Mac "m" series chips, blenders current implementation of OCIO doesnt seem to be supporting it well enough at the moment. So "built-in" transforms of OCIO are throwing weird errors like those.

Unfortunetly, I do not own any mac machines nor I am a "developer". So I cannot help much mitigating this issue. Only way to accomodate this is not to use any "built-in" transforms with the PixelManager which will make the download size huge and will be a step back to OCIO v1.x reducing the accuracty of the config drastically.

I really hope that blender devs are able to mitigate this issue as quickly as possible.
